---
- name: create multiple local users
  hosts: web
  vars_files:
    - vars/users_vars.yml
  tasks:
    - name: add webadmin group
      group:
        name: webadmin
        state: present

    - name: create user accounts
      user:
        name: "{{ item.username }}"
        group: webadmin
        password: "{{ 'redhat' | password_hash('sha512') }}"
        state: present
      loop: "{{ users }}"

    - name: add authorized keys
      authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', 'files/'+ item.username + '.key.pub') }}"
      loop: "{{ users }}"

    - name: modify sudo config to allow webadmin users sudo without a password
      copy:
        content: "%webadmin ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/webadmin
        mode: 0440
      notify: restart sshd

    - name: Permit SSH login without password for webadmin group
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^Match Group webadmin$'
        line: 'PasswordAuthentication no'
        state: present
      notify: restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
